services:
  nginx:
    build: ./nginx
    container_name: rainbowtext_proxy
    depends_on:
      - server
    ports:
      - 127.0.0.1:80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  server:
    build: .
    container_name: rainbowtext_server
    restart: always
    volumes:
      - .:/app
version: '3'
